name: yamagi-quake2-beidl
version: 7.20
grade: stable
summary: An enhanced version of id Software's Quake II.
description: |
  This is the Yamagi Quake II Client, an enhanced version of id Software's Quake II with focus on offline and coop gameplay. Both the gameplay and the graphics are unchanged, but many bugs if the last official release were fixed and some nice to have features like widescreen support and a modern OpenGL 3.2 renderer were added. Unlike most other Quake II source ports Yamagi Quake II is fully 64 bit clean. It works perfectly on modern processors and operating systems. Yamagi Quake II runs on nearly all common platforms; including FreeBSD, Linux, OpenBSD, Windows and OS X.
  
  This code is build upon Icculus Quake II, which itself is based on Quake II 3.21. Yamagi Quake II is released under the terms of the GPL version 2.
  
  Note to snap packagers:
   Additionally, other snaps can consume its content via a content interface plug. Consuming snaps could use following snapcraft.yaml snippet to add the interface.
  
  plugs:
    quake2-engine:
      content: quake2-engine
      interface: content
      target: $SNAP/quake2-engine
      default-provider: yamagi-quake2-beidl:quake2-engine
   
  Within the consuming snap the content would be exposed at "$SNAP/quake2-engine", ie:
    /snap/the-consuming-snap/current/quake2-engine
    /var/lib/snapd/snap/the-consuming-snap/current/quake2-engine
   
  Under certain circumstances it could be necessary to manually connect the interface, ie:
    snap connect the-consuming-snap:quake2-engine yamagi-quake2-beidl:quake2-engine
  
confinement: strict

apps:
  yquake2:
    command: desktop-launch quake2
    plugs: [ wayland, x11, desktop, home, opengl, pulseaudio, removable-media, network, joystick ]
  yquake2-launch:
    command: desktop-launch yquake2-launch
    plugs: [ wayland, x11, desktop, home, opengl, pulseaudio, removable-media, network, joystick ]

slots:
  quake2-engine:
    content: quake2-engine
    interface: content
    read:
      - $SNAP

parts:
  quake2:
    source: https://github.com/yquake2/yquake2.git
    source-type: git
    source-tag: QUAKE2_7_20
    plugin: cmake
    override-build: |
      mkdir build && cd build
      cmake .. -DCMAKE_INSTALL_PREFIX=
      make -j4
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mv release/* $SNAPCRAFT_PART_INSTALL/bin/
    build-packages:
      - make
      - build-essential
      - libgl1-mesa-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-net-dev
      - libpulse-dev
      - libvulkan-dev
      - libwayland-dev
      - libvorbis-dev
      - libmad0-dev
      - libogg-dev
      - libopenal-dev
      - zlib1g-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0
      - libpulse0
      - libvorbis0a
      - libmad0
      - libwayland-client0
      - libogg0
      - libopenal1
      - zlib1g
      - zenity
    prime:
      - bin/
      - lib/
      - usr/
    after: [ desktop-glib-only ]
  wrapper:
    source: .
    plugin: dump
    organize:
      yquake2-launch: bin/yquake2-launch
    after: [ quake2 ]
